[workspace]
resolver = "2"
members = [
    "photonic-sort-sys",
    "photonic-sort",
]

[workspace.package]
version = "1.3.1"
edition = "2021"
license = "MIT"
authors = [
    "Heywood Geblomi",
    "Grok (xAI)",
    "Harper",
    "Benjamin",
    "Lucas",
]
repository = "https://github.com/HeywoodGeblomi/PhotonicSort"
homepage = "https://heywoodgeblomi.github.io/PhotonicSort/"

[workspace.dependencies]
photonic-sort-sys = { path = "photonic-sort-sys", version = "1.3.1" }
